version: "3.8"

services:
  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfiles/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sgproject

  courses_backend:
    build:
      context: ./backend/courses
      dockerfile: Dockerfiles/Dockerfile
    networks:
      - sgproject

  gateway_backend:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfiles/Dockerfile
    networks:
      - sgproject

  customers_backend:
    build:
      context: ./backend/customers
      dockerfile: Dockerfiles/Dockerfile
    networks:
      - sgproject

  users_backend:
    build:
      context: ./backend/users
      dockerfile: Dockerfiles/Dockerfile
    networks:
      - sgproject

  enrollment_backend:
    build:
      context: ./backend/enrollment
      dockerfile: Dockerfiles/Dockerfile
    networks:
      - sgproject

  sql_backend:
    build:
      context: ./backend/sql
      dockerfile: Dockerfiles/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: sg@group1
      MYSQL_DATABASE: studio_ghibli_edu
      MYSQL_USER: sguser
      MYSQL_PASSWORD: sg@group1
    networks:
      - sgproject

networks:
  sgproject:
    driver: bridge
